language: python
python:
  - 2.7
services:
  - docker
before_install:
  - sudo apt -y install jq
install:
  - docker build -t pdns_recursor .
  - docker run -d --name pdns_recursor -v $PWD/config:/config pdns_recursor:latest
script:
  - docker images | grep -q pdns_recursor
  - docker ps | grep -q pdns_recursor
#  - test "$(dig @$(docker inspect pdns_recursor -f "{{json .NetworkSettings.Networks.bridge.IPAddress}}" | jq . -r) -t TXT localhost)" == "justsomestringtoreturnforautomatedtesting"
